Make python-venv compatible with non-osx-bash

diff --git a/portable/bin/python-venv b/portable/bin/python-venv
--- a/portable/bin/python-venv
+++ b/portable/bin/python-venv
@@ -1,24 +1,34 @@
 #!/bin/bash
 argcount=$#
 if [ $argcount -eq 0 ] ; then
-    echo "No virtualenv requested" 1>&2
+    echo "No script requested" 1>&2
     exit 1
 fi
 if [ -z "${WORKON_HOME}" ] ; then
     echo "WORKON_HOME is not set" 1>&2
     exit 1
 fi
-virtualenv_name="${1}"
-shift
-
+script_name="${1}"
+if [ ! -e "${script_name}" ] ; then
+    echo "File not found ${script_name}" 1>&2
+    exit 1
+fi
+virtualenv_name=$(cat "${script_name}" | grep '# *venv' | sed 's/^[ #]*venv //' | head -n 1)
+if [ -z "${virtualenv_name}" ] ; then
+    script_dir=$(dirname "${script_name}")
+    venv_config="${script_dir}/.venv"
+    if [ -e "${venv_config}" ] ; then
+        virtualenv_name=$(head -n 1 "${venv_config}")
+    fi
+fi
+if [ -z "${virtualenv_name}" ] ; then
+    echo "Could not determine virtualenv" 1>&2
+    exit 1
+fi
 virtualenv_path="${WORKON_HOME}/${virtualenv_name}/bin/python"
 if [ ! -e "${virtualenv_path}" ] ; then
     echo "Cannot find virtualenv ${virtualenv_name}" 1>&2
     exit 1
 fi
 
-if [ $argcount -eq 0 ] ; then
-    "${virtualenv_path}"
-else
-    "${virtualenv_path}" "${@}"
-fi
+"${virtualenv_path}" "${@}"
